name: Python application CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Hạ xuống 3.12 để đảm bảo độ tương thích

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Cài đặt trình duyệt cho playwright ngay trong môi trường CI
        playwright install chromium

    - name: Run tests
      run: pytest
      env:
        HEADLESS: "true"